[package]
name = "direct_payment_timesheets"
version = "0.0.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.31", features = ["bundled"] }
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5.0"
chrono = "0.4.45"
eframe = "0.33"
egui = "0.33"
pdf-extract = "0.7"
rfd = "0.15"
printpdf = "0.8"

