[package]
name = "direct_payment_timesheets"
version = "1.0.2"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/ArnieSkyNet/DirectPaymentTimesheets"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.31", features = ["backup", "bundled"] }
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5.0"
chrono = "0.4.45"
eframe = "0.33"
egui = "0.33"
pdf-extract = "0.7"
rfd = "0.15"
printpdf = { version = "0.8", features = ["png"] }
lettre = { version = "0.11", default-features = false, features = ["builder", "smtp-transport", "hostname", "pool", "tokio1-native-tls"] }
zip = "2.2"
sha2 = "0.10"

ureq = { version = "3", features = ["json"] }
semver = "1"

[dev-dependencies]
tempfile = "3"
