use rusqlite::{params, Connection, Result};

use crate::models::PersonalAssistant;

pub struct PersonalAssistantRepository {
    connection: Connection,
}

impl PersonalAssistantRepository {
    pub fn new(connection: Connection) -> Self {
        Self { connection }
    }

    pub fn insert(&self, assistant: &PersonalAssistant) -> Result<()> {
        self.connection.execute(
                                                                "
                                                                            INSERT INTO personal_assistants (
                                                                                            first_name,
                                                                                                            surname,
                                                                                                                            date_of_birth,
                                                                                                                                            national_insurance_number,
                                                                                                                                                            address,
                                                                                                                                                                            postcode,
                                                                                                                                                                                            telephone,
                                                                                                                                                                                                            email,
                                                                                                                                                                                                                            employment_status,
                                                                                                                                                                                                                                            sick_pay_enabled,
                                                                                                                                                                                                                                                            mileage_enabled,
                                                                                                                                                                                                                                                                            start_date,
                                                                                                                                                                                                                                                                                            signature
                                                )
                                                            VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13)
                                                                        ",
                                                                                    params![
                                                                                                        &assistant.first_name,
                                                                                                                        &assistant.surname,
                                                                                                                                        &assistant.address,
                                                                                                                                                        &assistant.postcode,
                                                                                                                                                                        &assistant.telephone,
                                                                                                                                                                                        &assistant.email,
                                                                                                                                                                                                        &assistant.employment_status,
                                                                                                                                                                                                                        assistant.sick_pay_enabled,
                                                                                                                                                                                                                                        assistant.mileage_enabled,
                                                                                                                                                                                                                                                        &assistant.start_date,
                                                                                                                                                                                                                                                                        &assistant.signature,
                                                                                    ],
                                                                                            )?;

        Ok(())
    }

    pub fn update(&self, assistant: &PersonalAssistant) -> Result<()> {
        self.connection.execute(
                                                                                                                                        "
                                                                                                                                                    UPDATE personal_assistants
                                                                                                                                                                SET
                                                                                                                                                                                first_name = ?1,
                                                                                                                                                                                                surname = ?2,
                                                                                                                                                                                                                date_of_birth = ?3,
                                                                                                                                                                                                                                national_insurance_number = ?4,
                                                                                                                                                                                                                                                address = ?5,
                                                                                                                                                                                                                                                                postcode = ?6,
                                                                                                                                                                                                                                                                                telephone = ?7,
                                                                                                                                                                                                                                                                                                email = ?8,
                                                                                                                                                                                                                                                                                                                employment_status = ?9,
                                                                                                                                                                                                                                                                                                                                sick_pay_enabled = ?10,
                                                                                                                                                                                                                                                                                                                                                mileage_enabled = ?11,
                                                                                                                                                                                                                                                                                                                                                                start_date = ?12,
                                                                                                                                                                                                                                                                                                                                                                                signature = ?13
                                                                                                                                                                                                                                                                                                                                                                                            WHERE id = ?14
                                                                                                                                                                                                                                                                                                                                                                                                        ",
                                                                                                                                                                                                                                                                                                                                                                                                                    params![
                                                                                                                                                                                                                                                                                                                                                                                                                                        &assistant.first_name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        &assistant.surname,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        &assistant.date_of_birth,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        &assistant.national_insurance_number,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        &assistant.address,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        &assistant.postcode,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        &assistant.telephone,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        &assistant.email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        &assistant.employment_status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        assistant.sick_pay_enabled,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        assistant.mileage_enabled,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        &assistant.start_date,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        &assistant.signature,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        assistant.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )?;

        Ok(())
    }

    pub fn get_all(&self) -> Result<Vec<PersonalAssistant>> {
        let mut statement = self.connection.prepare(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SELECT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                first_name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                surname,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                date_of_birth,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                national_insurance_number,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                address,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                postcode,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                telephone,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                employment_status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sick_pay_enabled,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mileage_enabled,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                start_date,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                signature
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FROM personal_assistants
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )?;

        let assistants = statement.query_map([], |row| {
            Ok(PersonalAssistant {
                id: row.get(0)?,
                first_name: row.get(1)?,
                surname: row.get(2)?,
                date_of_birth: row.get(3)?,
                national_insurance_number: row.get(4)?,
                address: row.get(5)?,
                postcode: row.get(6)?,
                telephone: row.get(7)?,
                email: row.get(8)?,
                employment_status: row.get(9)?,
                sick_pay_enabled: row.get::<_, i64>(10)? != 0,
                mileage_enabled: row.get::<_, i64>(11)? != 0,
                start_date: row.get(12)?,
                signature: row.get(13)?,
            })
        })?;

        let mut results = Vec::new();

        for assistant in assistants {
            results.push(assistant?);
        }

        Ok(results)
    }

    pub fn get_active(&self) -> Result<Vec<PersonalAssistant>> {
        let assistants = self.get_all()?;

        Ok(assistants
            .into_iter()
            .filter(|assistant| assistant.employment_status.as_deref() == Some("Active"))
            .collect())
    }


}
